name: version
on: 
  push:
    branches:
      - main
    paths:
      - 'service/**'
jobs:
  version_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: mr_push
        run: |
          echo "version_pipeline"
